name: "Storybook Tests"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: cd react-dev-app && npm install -f

      - name: Build Storybook
        run: cd react-dev-app && npm run build-storybook --quiet

      - name: Serve Storybook and run tests
        run: cd react-dev-app && ./test
